<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '15 Лет' => '',
    'About' => '',
    'Contact' => '',
    'Email' => '',
    'Login' => '',
    'Request password reset' => '',
    'Resend verification email' => '',
    'Reset password' => '',
    'Signup' => '',
    'Адресc' => '',
    'Активные области действия' => '',
    'Время работы' => '',
    'Имя' => '',
    'История компании' => '',
    'Клиентам' => '',
    'Код подтверждения' => '',
    'Контакты' => '',
    'Нефтебаза' => '',
    'О Компании' => '',
    'О компании' => '',
    'Связаться с нами' => '',
    'Сертификаты' => '',
    'Сообщение' => '',
    'Тема' => '',
    'Хранилище' => '',
    'смотреть' => '',
];
